name: Compile mMojo

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Compile mMojo
        uses: krn-sebastiaan/actions/compile@main
        with:
          build-xml-path: build-mojo.xml
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
